### ISSUE TITLE
Entity Reference

### ISSUE THREAD

**Issue by jim-rosales** [salahadem/prj-rev-bwfs-dasmoto#1]
Nice job using the ampersands [entity reference](https://developer.mozilla.org/en-US/docs/Glossary/Entity) to add it to your page!

https://github.com/salahadem/prj-rev-bwfs-dasmoto/blob/6beec59a922e79d4fc24fe78f4949fe07e0b3f8b/Dasmotos_Arts_Crafts/index.html#L4

**Comment by salahadem** [comment]
thanks.
