### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [salahadem/prj-rev-bwfs-dasmoto#5]
Grade: Meets Expectations

Summary:
Salah, congrats on finishing the Dasmoto project! You did an excellent job structuring your HTML code by making use of ids, classes, and various elements appropriately. Your CSS file was also absent of duplicate styles so great job there as well!

A couple of things I noticed were inconsistencies regarding formatting and the omittance of comments in your CSS file. Consider going over this article and this style guide that will help you improve the formatting of both your HTML and CSS file. For example, in your CSS file, I noticed that some elements were spaced using two spaces while others used 4. In your HTML file it is better to format paragraphs in the following way as is improves readability:
```HTML
<p>
  Qui quo sequi aspernatur facere sit. Odit vitae unde veniam. Possimus rerum autem saepe rerum accusamus. Ab qui aperiam omnis eos quas quae. Culpa accusamus aut vel. Voluptas fugiat tenetur deleniti.…
</p>
```
vs:
```HTML
<p> Qui quo sequi aspernatur facere sit. Odit vitae unde veniam. Possimus rerum autem saepe rerum accusamus. Ab qui aperiam omnis eos quas quae. Culpa accusamus aut vel. Voluptas fugiat tenetur deleniti.…</p>
```

As for comments on this project, your stylesheet was very short, but it is a good idea to always comments your code as it builds a great habit that you will use down the road as your progress as a developer.

**Comment by salahadem** [comment]
Good comment. I added comments to the style sheet.

**Comment by salahadem** [comment]
I uploaded changes after I made the changes. Both files index.html and style.css  were changed.
I had  to use the following to upload my changed to repository since myrepository was created for me  by Codeacademy. 
 git pull  --allow-unrelated-histories https://github.com/salahadem/prj-rev-bwfs-dasmoto.git
